### ISSUE TITLE
Manage credit card

### ISSUE THREAD

**Issue by Arcesilas** [Winbee/cashcash-desktop#11]
Hi, me again.

Do you think it could be possible/relevant to handle credit cards? Credit cards should have limits (payment and withdrawal).
For example, when creating a new transaction, we could define it used a specific credit card (payment or withdrawal).
This type (payment with a CC or a withdrawal with a CC) could be used in filters and allow the user to manage the credit card limits, which could be displayed on the dashboard.

I'm aware it's a big and non-essential feature, so if you don't intend to implement it, that's absolutely ok.

Also it makes me think that another "type" of transaction could be associated to a transaction: Credit card payment, Credit card withdrawal, direct debit ("prélèvement" in french), bank transfer, etc.

**Comment by Winbee** [comment]
Hi @Arcesilas,

Thanks for the ideas! Having a way to attached a credit card would be a nice feature indeed. To be honest, I'm not planning on working on the project too hard in the short term but I'll keep it in mind. Of course, don't hesitate to send some PRs if you feel inspired.
About adding more "type" of transactions, I'm more leaning toward keeping them at minimum. They are meant to just define a movement from an account of a certain type to another account of certain type. 'Credit card payment, Credit card withdrawal, direct debit, bank transfer' would all be similar to an 'Expense' meaning a transfer from an ASSET account to an EXPENSE account. However having a subtype concept listing this stuffs could work.
