### ISSUE TITLE
About asset transfer

### ISSUE THREAD

**Issue by Arcesilas** [Winbee/cashcash-desktop#12]
About asset transfer, I see we MUST specify an "outgoing account" ("compte sortant" in french). The accounts that are proposed are my internal accounts... What if I want to transfer money to my mother? How should I create the transaction? It's possible to choose an external account if it's just an expense. But when I transfer money to my mother or a friend, it's not exactly an expense. It can be anything: gift, repayment, loan/credit, etc. Maybe I'm just meticulous with words and should just create an expense?

Cashcash does not use the concept of third party (who is receiving / sending the money). And that's fine, since it can be written in the description or in the details. However, third parties would allow the user to use them in filters or to choose a recipient for a bank transfer (instead of an account).

**Comment by Winbee** [comment]
Yes, the term Expense is quite narrow or misleading I agree. I meant any movement of money from your asset accounts to an external account of any kind. Expense came to my mind but there is probably better out there :-). If you really want to distinguish between expense and other types, I would suggest reorganizing the expense folders in the way you like. Technically the transaction will still be an expense but the accounts in which the money arrives could be living in a different folder.

I like your concept of third party. I didn't thought about it before but I can imagine it would be a common need. I'm planning to create a way to add tags to transactions. I think it could also tackle this use case.

**Comment by Winbee** [comment]
Hello @Arcesilas, for info, I finally found the time to add some transaction tags in the app.
