### ISSUE TITLE
Allow to not set a time for a transaction

### ISSUE THREAD

**Issue by Arcesilas** [Winbee/cashcash-desktop#14]
Me again :)
I'm not sure the time is really relevant. Maybe for a company, but for an individual, I don't see the point.
When we create a transaction which occured yesterday, by default the time is the current time,which is not relevant and I don't know anyone who really cares about the time the transaction occured.
It would be nice if we could have an option to not save the time (it could be set to 00:00 by default if it's required for the db). Transactions should then be displayed in the order they where created (or by name, I'm not sure whether it's importantor not)

**Comment by Winbee** [comment]
Totally agree. It was super simple to change so it is now the default with the version 1.0.30.

Thanks @Arcesilas for the feedbacks. Keep them coming.

**Comment by Arcesilas** [comment]
Great, thanks again!
