### ISSUE TITLE
How do I delete an account?

### ISSUE THREAD

**Issue by Arcesilas** [Winbee/cashcash-desktop#9]
I'm giving a try to this nice app and I'd like to delete the internal account "Cash in EUR" because to manage cash, I open my wallet.

When I click on the delete icon, after confirmation, I get an error message : "Can't delete this CashAccount because other objects depend on it." What kind of objects depend on this account? Is there anything to do before I'm able to delete it?

Thanks!

**Comment by Winbee** [comment]
Hi @Arcesilas, I think you spotted a bug. Thanks for bringing it up!
I've pushed a fix and I'm now trying to release a new version.

**Comment by Arcesilas** [comment]
Great! Thanks!
